### ISSUE TITLE
[BUG] `Table {name} does not support truncate in batch mode` in pyspark 3.5.6 when append after overwrite

### ISSUE THREAD

**Issue by harupy** [delta-io/delta#4671]
#### Which Delta project/connector is this regarding?

- [x] Spark
- [ ] Standalone
- [ ] Flink
- [ ] Kernel
- [ ] Other (fill in here)

#### Steps to reproduce

Run this code with pyspark 3.5.6:

```python
import pyspark
from pyspark.sql import SparkSession

print(pyspark.__version__)
with (
    SparkSession.builder.master("local[*]")
    .config("spark.jars.packages", "io.delta:delta-spark_2.12:3.3.1")
    .config("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension")
    .config("spark.sql.catalog.spark_catalog", "org.apache.spark.sql.delta.catalog.DeltaCatalog")
    .getOrCreate()
) as spark:
    data = [{"name": "foo", "age": 1}]
    df1 = spark.createDataFrame(data)
    df1.write.format("delta").option("mergeSchema", "true").mode("overwrite").saveAsTable("test")
    df2 = spark.createDataFrame(data)
    df2.write.format("delta").option("mergeSchema", "true").mode("append").saveAsTable("test")
```

This code works fine in pyspark 3.5.5.

#### Observed results

```
:: loading settings :: url = jar:file:/Users/harutaka.kawamura/.cache/uv/archive-v0/46WO7IHaxQZgEyU5EZgHQ/lib/python3.9/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
Ivy Default Cache set to: /Users/harutaka.kawamura/.ivy2/cache
The jars for the packages stored in: /Users/harutaka.kawamura/.ivy2/jars
io.delta#delta-spark_2.12 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-6b3984a2-8650-4b28-8cc0-eba5b1197803;1.0
        confs: [default]
        found io.delta#delta-spark_2.12;3.3.1 in central
        found io.delta#delta-storage;3.3.1 in central
        found org.antlr#antlr4-runtime;4.9.3 in local-m2-cache
:: resolution report :: resolve 89ms :: artifacts dl 4ms
        :: modules in use:
        io.delta#delta-spark_2.12;3.3.1 from central in [default]
        io.delta#delta-storage;3.3.1 from central in [default]
        org.antlr#antlr4-runtime;4.9.3 from local-m2-cache in [default]
        ---------------------------------------------------------------------
        |                  |            modules            ||   artifacts   |
        |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
        ---------------------------------------------------------------------
        |      default     |   3   |   0   |   0   |   0   ||   3   |   0   |
        ---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent-6b3984a2-8650-4b28-8cc0-eba5b1197803
        confs: [default]
        0 artifacts copied, 3 already retrieved (0kB/3ms)
25/05/30 18:05:21 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
25/05/30 18:05:23 ERROR Utils: Aborting task
org.apache.spark.sql.AnalysisException: Table test does not support truncate in batch mode.;
OverwriteByExpression RelationV2[age#6L, name#7] spark_catalog.default.test test, true, [mergeSchema=true], false
+- LogicalRDD [age#0L, name#1], false

        at org.apache.spark.sql.errors.QueryCompilationErrors$.unsupportedTableOperationError(QueryCompilationErrors.scala:1277)
        at org.apache.spark.sql.errors.QueryCompilationErrors$.unsupportedTruncateInBatchModeError(QueryCompilationErrors.scala:1297)
        at org.apache.spark.sql.execution.datasources.v2.TableCapabilityCheck$.$anonfun$apply$1(TableCapabilityCheck.scala:61)
        at org.apache.spark.sql.execution.datasources.v2.TableCapabilityCheck$.$anonfun$apply$1$adapted(TableCapabilityCheck.scala:40)
        at org.apache.spark.sql.catalyst.trees.TreeNode.foreach(TreeNode.scala:234)
        at org.apache.spark.sql.execution.datasources.v2.TableCapabilityCheck$.apply(TableCapabilityCheck.scala:40)
        at org.apache.spark.sql.execution.datasources.v2.TableCapabilityCheck$.apply(TableCapabilityCheck.scala:32)
        at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$60(CheckAnalysis.scala:822)
        at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$60$adapted(CheckAnalysis.scala:822)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis0(CheckAnalysis.scala:822)
        at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis0$(CheckAnalysis.scala:197)
        at org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis0(Analyzer.scala:202)
        at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis(CheckAnalysis.scala:193)
        at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis$(CheckAnalysis.scala:171)
        at org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis(Analyzer.scala:202)
        at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$1(Analyzer.scala:225)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:330)
        at org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:222)
        at org.apache.spark.sql.execution.QueryExecution.$anonfun$analyzed$1(QueryExecution.scala:77)
        at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:138)
        at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$2(QueryExecution.scala:219)
        at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:546)
        at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:219)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
        at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:218)
        at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:77)
        at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:74)
        at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:85)
        at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:83)
        at org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:142)
        at org.apache.spark.sql.execution.datasources.v2.V2CreateTableAsSelectBaseExec.$anonfun$writeToTable$1(WriteToDataSourceV2Exec.scala:587)
        at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1397)
        at org.apache.spark.sql.execution.datasources.v2.V2CreateTableAsSelectBaseExec.writeToTable(WriteToDataSourceV2Exec.scala:579)
        at org.apache.spark.sql.execution.datasources.v2.V2CreateTableAsSelectBaseExec.writeToTable$(WriteToDataSourceV2Exec.scala:572)
        at org.apache.spark.sql.execution.datasources.v2.AtomicReplaceTableAsSelectExec.writeToTable(WriteToDataSourceV2Exec.scala:186)
        at org.apache.spark.sql.execution.datasources.v2.AtomicReplaceTableAsSelectExec.run(WriteToDataSourceV2Exec.scala:221)
        at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result$lzycompute(V2CommandExec.scala:43)
        at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result(V2CommandExec.scala:43)
        at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.executeCollect(V2CommandExec.scala:49)
        at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:107)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:125)
        at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:201)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:108)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
        at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:66)
        at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:107)
        at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:98)
        at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:461)
        at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(origin.scala:76)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:461)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:32)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:437)
        at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:98)
        at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:85)
        at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:83)
        at org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:142)
        at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:869)
        at org.apache.spark.sql.DataFrameWriter.saveAsTable(DataFrameWriter.scala:645)
        at org.apache.spark.sql.DataFrameWriter.saveAsTable(DataFrameWriter.scala:579)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
        at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
        at java.base/java.lang.Thread.run(Thread.java:840)
Traceback (most recent call last):
  File "/Users/harutaka.kawamura/Desktop/repositories/mlflow/a.py", line 14, in <module>
    df1.write.format("delta").option("mergeSchema", "true").mode("overwrite").saveAsTable("test")
  File "/Users/harutaka.kawamura/.cache/uv/archive-v0/46WO7IHaxQZgEyU5EZgHQ/lib/python3.9/site-packages/pyspark/sql/readwriter.py", line 1586, in saveAsTable
    self._jwrite.saveAsTable(name)
  File "/Users/harutaka.kawamura/.cache/uv/archive-v0/46WO7IHaxQZgEyU5EZgHQ/lib/python3.9/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
  File "/Users/harutaka.kawamura/.cache/uv/archive-v0/46WO7IHaxQZgEyU5EZgHQ/lib/python3.9/site-packages/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.AnalysisException: Table test does not support truncate in batch mode.;
OverwriteByExpression RelationV2[age#6L, name#7] spark_catalog.default.test test, true, [mergeSchema=true], false
+- LogicalRDD [age#0L, name#1], false
```

#### Further details

No Error

### Environment information

* Delta Lake version: 3.3.1?
* Spark version: 3.5.6
* Scala version: 2.12

### Willingness to contribute

The Delta Lake Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the Delta Lake code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the Delta Lake community.
- [x] No. I cannot contribute a bug fix at this time.

**Comment by ElliotNguyen68** [comment]
Hi @harupy , I am also facing this same issue, revert to pyspark 3.5.5 make it work as normal

**Comment by mr-illu-minati** [comment]
Hi @harupy same here !

**Comment by dtheodor** [comment]
Related? https://github.com/apache/spark/pull/50739

**Comment by gerashegalov** [comment]
SQL one-liner reproducer for this bug
```sql
>>> spark.sql("CREATE OR REPLACE TABLE x USING DELTA AS SELECT * FROM VALUES (1, 'SF')")
25/07/19 23:58:17 ERROR Utils: Aborting task
org.apache.spark.sql.AnalysisException: Table x does not support truncate in batch mode.;
OverwriteByExpression RelationV2[col1#16, col2#17] spark_catalog.default.x x, true, false
+- Project [col1#14, col2#15]
   +- LocalRelation [col1#14, col2#15]
```

**Comment by gkpanda4** [comment]
This change should fix the issue in Spark 3.5.6
https://github.com/delta-io/delta/pull/4919

**Comment by vkorukanti** [comment]
Fix is merged into branch-3.3. The problem doesn't exist in the master.

**Comment by sethstoudenmier** [comment]
This seems to be fixed when using Spark SQL, but the dataframe API is still running into the issue. The example initially shared in the issue still raises the following:
```
pyspark.errors.exceptions.captured.AnalysisException: Table test does not support truncate in batch mode.;
OverwriteByExpression RelationV2[age#812L, name#813] spark_catalog.default.test test, true, [mergeSchema=true], false
+- LogicalRDD [age#806L, name#807], false
```

**Comment by Stepanov-hub** [comment]
I'm experiencing the same issue in spark 4.0.0 as well.
org.apache.spark.sql.AnalysisException: [UNSUPPORTED_FEATURE.TABLE_OPERATION] The feature is not supported: Table test_a does not support truncate in batch mode. Please check the current catalog and namespace to make sure the qualified table name is expected, and also check the catalog implementation which is configured by "spark.sql.catalog". SQLSTATE: 0A000;

**Comment by dtheodor** [comment]
@vkorukanti Please reopen this

**Comment by danielliu-eon** [comment]
I am also still experiencing this issue with the DataFrame API. This issue is still not resolved.

**Comment by danielliu-eon** [comment]
> I am also still experiencing this issue with the DataFrame API. This issue is still not resolved.

The fix does resolve the issues with the DataFrame API, but it is not in a release version for Delta 3.3.

**Comment by stawo** [comment]
Experiencing the same issue with the DataFrame API using PySpark.
Using:
- `pyspark 3.5.8`
- `delta-spark 3.3.1`

**Comment by JevonCowell** [comment]
+1 Issue still persist in 3.5.8

**Comment by cao-zheng** [comment]
same issue 
pyspark 3.5.8
delta-spark 3.3.2

**Comment by philo-he** [comment]
This seems fixed in the 3.3 branch and targeted for the unreleased 3.3.3. Any idea when 3.3.3 will be released? cc @vkorukanti

**Comment by felipepessoto** [comment]
IIRC most of branches have unreleased fixes. Probably we will never have a 3.3.3.

I haven't seen @vkorukanti here for a while. Maybe @openinx or @timothyw553 have more info about 3.3.3.
