### ISSUE TITLE
[BUG]  com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: io/delta/storage/LogStore

### ISSUE THREAD

**Issue by ven201870** [delta-io/delta#5531]
#### Which Delta project/connector is this regarding?
EMR version  - emr-7.10.0
Spark 3.5.5
delta version - delta-spark_2.12-3.3.2.jar
Scala version - 2.12

- [x ] Spark
- [ ] Standalone
- [ ] Flink
- [ ] Kernel
- [ ] Other (fill in here)

### Describe the problem
Hi Team

I am getting the below issue when I am trying to run my Scala spark application via EMR by adding steps

#### Steps to reproduce

<img width="1015" height="520" alt="Image" src="https://github.com/user-attachments/assets/aa3678c3-ae49-4165-83fa-6899e7b1952d" />

I have tried passing --packages io.delta:delta-storage:3.3.2 in spark submit still facing the same issue.

### Environment information

* Delta Lake version: delta-spark_2.12-3.3.2.jar
* Spark version: 3.5.5
* Scala version: 2.12

### Willingness to contribute

The Delta Lake Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the Delta Lake code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the Delta Lake community.
- [ ] No. I cannot contribute a bug fix at this time.

**Comment by AnudeepKonaboina** [comment]
Hey @ven201870 ,

The root problem is `java.lang.NoClassDefFoundError: io/delta/storage/LogStore,` which happens because delta-storage JAR  is not on the classpath when using Delta 2.3+ / 3.x.

**To fix it correctly:**
Always include both artifacts together:

- Maven/SBT:

    -    delta-spark_<scala-version>:<delta-version>
    -    delta-storage:<delta-version>

- spark-shell / spark-submit:
           --jars /path/delta-spark_2.12:3.3.2,/path/delta-storage:3.3.2

- delta-spark and delta-storage must have the same Delta version (e.g. both 3.3.2).

I have reproed it internally , when i didnt use storage jar it failed with the same issue

```
[root@hadoop /]# spark-shell   --jars /tmp/delta-spark_2.13-3.4.0-SNAPSHOT.jar   --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension   --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog
25/11/26 13:11:39 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 3.5.2
      /_/
         
Using Scala version 2.13.8 (OpenJDK 64-Bit Server VM, Java 17.0.9)
Type in expressions to have them evaluated.
Type :help for more information.
Spark context Web UI available at http://hadoop.spark:4040
Spark context available as 'sc' (master = local[*], app id = local-1764162701993).
Spark session available as 'spark'.

---
--
com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: io/delta/storage/LogStore
Please ensure that the delta-storage dependency is included.

If using Python, please ensure you call `configure_spark_with_delta_pip` or use
`--packages io.delta:delta-spark_<scala-version>:<delta-lake-version>`.
See https://docs.delta.io/latest/quick-start.html#python.

More information about this dependency and how to include it can be found here:
https://docs.delta.io/latest/porting.html#delta-lake-1-1-or-below-to-delta-lake-1-2-or-above.

  at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2261)
  at com.google.common.cache.LocalCache.get(LocalCache.java:4000)
  at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4789)
  at org.apache.spark.sql.delta.DeltaLog$.getDeltaLogFromCache$1(DeltaLog.scala:1008)
  at org.apache.spark.sql.delta.DeltaLog$.initializeDeltaLog$1(DeltaLog.scala:1019)
  at org.apache.spark.sql.delta.DeltaLog$.apply(DeltaLog.scala:1030)
  at org.apache.spark.sql.delta.DeltaLog$.forTable(DeltaLog.scala:814)
  at org.apache.spark.sql.delta.util.Utils$.$anonfun$getDeltaLogFromTableOrPath$2(Utils.scala:71)
  at scala.Option.getOrElse(Option.scala:201)

```

**After adding the jar :**

```
[root@hadoop /]# spark-shell   --jars /tmp/delta-spark_2.13-3.4.0-SNAPSHOT.jar,/tmp/delta-storage-3.4.0-SNAPSHOT.jar   --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension   --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog
25/11/26 13:21:14 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 3.5.2
      /_/
         
Using Scala version 2.13.8 (OpenJDK 64-Bit Server VM, Java 17.0.9)
Type in expressions to have them evaluated.
Type :help for more information.
Spark context Web UI available at http://hadoop.spark:4040
Spark context available as 'sc' (master = local[*], app id = local-1764163276797).
Spark session available as 'spark'.

scala> 

```

**NOTE**:  Make sure there is no space in between the --jars option. Use  `--jars /tmp/delta-spark_2.13-3.4.0-SNAPSHOT.jar,/tmp/delta-storage-3.4.0-SNAPSHOT.jar`

So i believe its a classpath issue not a code issue .

**Comment by AnudeepKonaboina** [comment]
Hello @ven201870 , is this issue resolved?

**Comment by raveeram-db** [comment]
thanks @AnudeepKonaboina ! Do our OSS docs need to be updated here?

**Comment by AnudeepKonaboina** [comment]
Hi @raveeram-db ! I believe yes.. But i am not sure where exactly to add. Is it in https://github.com/delta-io/delta/blob/master/docs/src/content/docs/delta-storage.mdx ?
Let  me know where exactly i should add it and can raise a PR with the change

**Comment by AnudeepKonaboina** [comment]
Closing this as the issue is addressed and the docs are update !

**Comment by techkuz** [comment]
still fails with 3.5.6 spark, using both
io.delta:delta-spark_2.13:3.3.2; io.delta:delta-storage:3.3.2
